server:
  port: 8082
spring:
  application:
    name: User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: Mysql@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


